[tox]
minversion = 4
envlist = py310, py311, py312, py313, lint

[testenv]
extras = test
commands = python -m unittest discover -s test -v

[testenv:lint]
basepython = python3
extras = test,dev
commands =
  black --check finqir test tools docs
  pylint --persistent=n -rn finqir test tools
  mypy finqir test tools
  python tools/verify_headers.py finqir test tools

[testenv:coverage]
basepython = python3
extras = test
commands =
  coverage run --source finqir -m unittest discover -s test -v
  coverage report

[testenv:docs]
basepython = python3
extras = docs
commands = sphinx-build -j auto -W -T --keep-going -b html docs/ docs/_build/html
